// Complete Global Search Index - Static Guide Go items + All pages
const searchIndex = [
  // Home carousel items
  {
    id: 'home-uc-mission',
    name: 'UC Mission',
    type: 'image',
    path: 'UC MVH/ucMission.png',
    page: 'Home',
  },
  {
    id: 'home-uc-vision',
    name: 'UC Vision',
    type: 'image',
    path: 'UC MVH/ucVision.png',
    page: 'Home',
  },
  {
    id: 'home-uc-goals',
    name: 'UC Goals',
    type: 'image',
    path: 'UC MVH/ucGoals.png',
    page: 'Home',
  },
  {
    id: 'home-uc-hymn',
    name: 'UC Hymn',
    type: 'image',
    path: 'UC MVH/ucHymn.png',
    page: 'Home',
  },

  // CCS Department carousel
  {
    id: 'ccs-mission',
    name: 'CCS Mission',
    type: 'image',
    path: 'CCS MV/ccsMission.png',
    page: 'CCS Department',
  },
  {
    id: 'ccs-vision',
    name: 'CCS Vision',
    type: 'image',
    path: 'CCS MV/ccsVision.png',
    page: 'CCS Department',
  },
  {
    id: 'ccs-goals',
    name: 'CCS Goals',
    type: 'image',
    path: 'CCS MV/ccsGoals.png',
    page: 'CCS Department',
  },

  // Tech Tutorial pages
  {
    id: 'tech-tutorial',
    name: 'Tech Tutorial',
    type: 'page',
    path: '../Tech Tutorial/techTut.html',
    page: 'Tech Tutorial',
  },

  // Navigation pages
  {
    id: 'nav-guide-go',
    name: 'Guide GO',
    type: 'page',
    path: '../../Guide Go/guideGo.html',
    page: 'Guide GO',
  },
  {
    id: 'nav-home',
    name: 'Home',
    type: 'page',
    path: 'index.html',
    page: 'Home',
  },
  {
    id: 'ccs-dept',
    name: 'CCS Department',
    type: 'page',
    path: '../CCS Department/ccsDept.html',
    page: 'CCS Department',
  },
  {
    id: 'lost-found',
    name: 'Lost and Found',
    type: 'page',
    path: '../Lost and Found/lostnFound.html',
    page: 'Lost and Found',
  },

  // ✅ Guide Go gallery items - matched from gridData (all 20 items)
  {
    id: 'guide-accounting',
    name: 'ACCOUNTING',
    type: 'page',
    path: '../../Guide Go/guideGo.html',
    page: 'Guide Go',
  },
  {
    id: 'guide-cashier',
    name: 'CASHIER',
    type: 'page',
    path: '../../Guide Go/guideGo.html',
    page: 'Guide Go',
  },
  {
    id: 'guide-college-reg',
    name: 'COLLEGE REGISTRAR',
    type: 'page',
    path: '../../Guide Go/guideGo.html',
    page: 'Guide Go',
  },
  {
    id: 'guide-csu',
    name: 'CIVIL SECURITY UNIT (CSU)',
    type: 'page',
    path: '../../Guide Go/guideGo.html',
    page: 'Guide Go',
  },
  {
    id: 'guide-textbook',
    name: 'TEXTBOOK SECTION',
    type: 'page',
    path: '../../Guide Go/guideGo.html',
    page: 'Guide Go',
  },
  {
    id: 'guide-seniorhigh-reg',
    name: 'SENIOR HIGH SCHOOL REGISTRAR',
    type: 'page',
    path: '../../Guide Go/guideGo.html',
    page: 'Guide Go',
  },
  {
    id: 'guide-eteeap',
    name: 'ETEEAP OFFICE',
    type: 'page',
    path: '../../Guide Go/guideGo.html',
    page: 'Guide Go',
  },
  {
    id: 'guide-edp-it',
    name: 'EDP / IT OFFICE',
    type: 'page',
    path: '../../Guide Go/guideGo.html',
    page: 'Guide Go',
  },
  {
    id: 'guide-clinic',
    name: 'UNIVERSITY CLINIC',
    type: 'page',
    path: '../../Guide Go/guideGo.html',
    page: 'Guide Go',
  },
  {
    id: 'guide-college-guidance',
    name: 'COLLEGE GUIDANCE SERVICES CENTER',
    type: 'page',
    path: '../../Guide Go/guideGo.html',
    page: 'Guide Go',
  },
  {
    id: 'guide-chapel',
    name: 'CHAPEL',
    type: 'page',
    path: '../../Guide Go/guideGo.html',
    page: 'Guide Go',
  },
  {
    id: 'guide-campus-ministry',
    name: 'CAMPUS MINISTRY OFFICE',
    type: 'page',
    path: '../../Guide Go/guideGo.html',
    page: 'Guide Go',
  },
  {
    id: 'guide-ims',
    name: 'IMS OFFICE',
    type: 'page',
    path: '../../Guide Go/guideGo.html',
    page: 'Guide Go',
  },
  {
    id: 'guide-library',
    name: 'LIBRARY',
    type: 'page',
    path: '../../Guide Go/guideGo.html',
    page: 'Guide Go',
  },
  {
    id: 'guide-dean',
    name: "DEAN'S OFFICE (CCS)",
    type: 'page',
    path: '../../Guide Go/guideGo.html',
    page: 'Guide Go',
  },
  {
    id: 'guide-faculty',
    name: 'FACULTY ROOM (CCS)',
    type: 'page',
    path: '../../Guide Go/guideGo.html',
    page: 'Guide Go',
  },
  {
    id: 'guide-psits',
    name: 'PSITS OFFICE',
    type: 'page',
    path: '../../Guide Go/guideGo.html',
    page: 'Guide Go',
  },
  {
    id: 'guide-scholarship',
    name: 'SCHOLARSHIP OFFICE',
    type: 'page',
    path: '../../Guide Go/guideGo.html',
    page: 'Guide Go',
  },
  {
    id: 'guide-sao',
    name: 'STUDENT AFFAIR OFFICE (SAO)',
    type: 'page',
    path: '../../Guide Go/guideGo.html',
    page: 'Guide Go',
  },
  {
    id: 'guide-nstp',
    name: 'NSTP OFFICE',
    type: 'page',
    path: '../../Guide Go/guideGo.html',
    page: 'Guide Go',
  },
];
